version: "3.8"
services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: 
      - fastfood
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - pgdb
    networks: 
      - fastfood
networks:
  fastfood:
    driver: bridge